### PR TITLE
Don't bail out on missing app-info file

### PR DESCRIPTION
**Pull request by barthalion**

### CODE REVIEW

**Comment by ramcq** [comment]
We might want to tighten this up because we don't want to leave any metainfo/app-info/... in the Flatpaks which get merged into the appstream but don't get found and patched to have true storefront info (verified, pricing, etc). Do we need to check any legacy paths that appstream-cli would still pick up? Or is this definitely the only path Flatpak will export?

**Comment by barthalion** [comment]
Flatpak also exports appdata/metainfo, but I have no idea what for and what consumes it. The combined AppStream file is the one consumed by frontends.

**Comment by ramcq** [comment]
Yeah, I think we need to make sure we are checking/filtering all paths that the appstream tools will collect into our official appstream. Hopefully @jameswestman can take a look when he awakes.

**Comment by ramcq** [comment]
This hook is a "security" filter though, from this point on, only true data we have checked should remain. We should explicitly remove the legacy paths at this point if we only want there to be one valid path through the system. ie we don't want to be leaving false vending data in a path that some people do use just because it's not the one we use.

**Pull request merged**
